# Generated by Django 3.0.7 on 2020-09-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryl1',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='categoryl2',
            unique_together={('slug', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('slug', 'category')},
        ),
    ]
