# Generated by Django 3.0.7 on 2020-09-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200905_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_small',
            field=models.ImageField(blank=True, upload_to='shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_thumb',
            field=models.ImageField(blank=True, upload_to='shop'),
        ),
    ]
